/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'atk_f407' 
 * Target:  'LVGL' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* LVGL::LVGL&LVGL9:Essential@9.3.0-dev2 */
/*! \brief Enable LVGL */
#define RTE_GRAPHICS_LVGL


#endif /* RTE_COMPONENTS_H */
